services:
  - type: web
    name: scalar-ag-backend
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0
